apiVersion: apps/v1
kind: Deployment
metadata:
  name: fire-refuge-deployment
  namespace: fire-refuge-prod
  labels:
    app: fire-refuge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fire-refuge
  template:
    metadata:
      labels:
        app: fire-refuge
    spec:
      containers:
        - name: web-server
          image: mvpstudio/fire-refuge:Nov21
          resources:
            limits:
              cpu: 0.5
              memory: 500Mi
            requests:
              cpu: 0.5
              memory: 500Mi
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
